/** Math */
export * from "./math"
/* Array */
export * from "./array"
/* Base */
export { default as observe } from "./observe"
export { default as observable } from "./observable"
export { default as resolve } from "../resolve"
export { default as compose } from "./compose"
export { default as pipe } from "./pipe"
export { default as composePromise } from "./composePromise"
export { default as pipePromise } from "./pipePromise"
export { default as pipePath } from "./pipePath"
export { default as scan } from "./scan"
export { default as type } from "./type"

export { default as assoc } from "./assoc"
export { default as assocPath } from "./assocPath"

export { default as invoker } from "./invoker"

export { default as call } from "./call"
export { default as apply } from "./apply"

export { default as to } from "./to"

export { default as rearg } from "./rearg"
export { default as methods } from "./methods"
export { default as reorder } from "./reorder"

export { default as map } from "./map"
export { default as sort } from "./sort"
export { default as sortBy } from "./sortBy"
export { default as sortWith } from "./sortWith"

export { default as get } from "./get"
export { default as set } from "./set"
export { default as has } from "./has"
export { default as use } from "./use"

export { default as prop } from "./get"

export { default as delay } from "./delay"
export { default as print } from "./print"

export { default as ife } from "./ifElse"

export { default as o } from "./o"
export { default as times } from "./times"
export { default as view } from "./view"
export { default as nth } from "./nth"
export { default as iis } from "./is"
export { default as last } from "./last"
export { default as keys } from "./keys"
export { default as props } from "./props"
export { default as pluck } from "./pluck"
export { default as slice } from "./slice"
export { default as toString } from "./toString"
export { default as tag } from "./template"
export { default as take } from "./take"
export { default as drop } from "./drop"
export { default as dropLast } from "./dropLast"

export { default as isNil } from "./isNil"
export { default as getPath } from "./path"
export { default as arg } from "./arg"
export { default as flip } from "./flip"

export { default as reverse } from "./reverse"
export { default as pick } from "./pick"
export { default as reduce } from "./reduce"
export { default as diff } from "./diff"
export { default as contains } from "./contains"
export { default as indexOf } from "./indexOf"
export { default as identical } from "./identical"
export { default as first } from "./first"
export { default as eq } from "./eq"
export { default as and } from "./and"
export { default as cond } from "./cond"
export { default as constant } from "./constant"
export { default as uniq } from "./uniq"
export { default as identity } from "./identity"
export { default as tap } from "./tap"
export { default as defaultTo } from "./defaultTo"
export { default as log } from "./log"
export { default as as } from "./as"
export { default as tail } from "./tail"
export { default as or } from "./or"
export { default as toArray } from "./toArray"
export { default as proxy } from "./proxy"
export { default as assign } from "./assign"
export { default as stringify } from "./stringify"
export { default as toLower } from "./toLower"
export { default as toUpper } from "./toUpper"
export { default as replace } from "./replace"

export { default as lt } from "./lt"
export { default as gt } from "./gt"
